info: "Extracting punishments from Dutch criminal law cases"

# The code base contains 'is None' checks
# To return a NoneType from the config, either comment out a line or pass null

defaults:
    - _self_
    - dataloader: default
    - caseparser: default
    - query: default

# https://hydra.cc/docs/next/tutorials/basic/running_your_app/working_directory/
# This is the *original* working directory (Hydra hijacks the cwd and makes its own)
# You can also get this in Python with `from hydra.utils import get_original_cwd`
original_work_dir: ${hydra:runtime.cwd}

# path to folder with data
data_dir: ${original_work_dir}/data

# pretty print config at the start of the run using Rich library
print_config: True

# disable python warnings 
ignore_warnings: False

# Debug mode  (override from command line: python main.py debug=true)
debug: False

# Skip querying and download cases if they are already on disk
# python main.py skip_query=true
skip_query: False

# Hydra hijacks the run directory
# You can override it here
# TODO the main log is dumped in the working directory, but I want it in output_subdir instead
hydra:
    run:
        dir: ${original_work_dir}
    output_subdir: logs/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
    verbose: False  # set log level of all loggers to debug
