level: 'section'  # paragraph
include_section_titles: True  # When False, you'll have slightly more empty columns, meaning that some sections only have a title
include_procedures: ['Eerste aanleg - meervoudig', 'Op tegenspraak', 'Eerste aanleg - enkelvoudig', 'Proces-verbaal', 'Tussenuitspraak', 'Mondelinge uitspraak']
data_key: 'data'  # key under which to store data in the csv/dataframe
skip: False
