reduce_to_sentences: False
cased_data: True
target: 'type'  # column name of target class
binary_label: null  #'overwegingen'; specify a value x of the target column; will convert target to x vs. non-x
drop_columns: ['Unnamed: 0']
drop_types: ['bijlage']  # ['overig', 'bijlage']
data_key: 'data'
data_fn: 'parsed_data.csv'
min_samples_per_class: 10  # if null, no rows will be dropped
