info: Extracting punishments from Dutch criminal law cases
original_work_dir: ${hydra:runtime.cwd}
data_dir: ${original_work_dir}/data
print_config: true
ignore_warnings: false
debug: false
dataloader:
  reduce_to_sentences: false
  cased_data: true
  binary_labels: false
  drop_overig: false
  target: type
  data_key: data
